/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutInputNumber: typeof import('@nutui/nutui-taro')['InputNumber']
    NutRate: typeof import('@nutui/nutui-taro')['Rate']
  }
}
